title: a developer
description: A blog about Java, programming, and software development
url: "https://isaacnote.com"
baseurl: ""

remote_theme: mmistakes/minimal-mistakes
minimal_mistakes_skin: "dark"

timezone: Asia/Taipei
encoding: utf-8

permalink: /:year/:month/:day/:title/

paginate: 20
paginate_path: "/page/:num/"

search: true

analytics:
  provider: "google-gtag"
  google:
    tracking_id: "G-0J8SWP88Y4"

author:
  name: "a developer"

plugins:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-feed
  - jekyll-include-cache

include:
  - _pages

defaults:
  - scope:
      path: "_pages"
      type: "pages"
    values:
      layout: "single"
  - scope:
      path: "_posts"
      type: "posts"
    values:
      layout: "single"

category_archive:
  type: liquid
  path: /categories/
tag_archive:
  type: liquid
  path: /tags/

after_footer_scripts:
  - /assets/js/calendar-widget.js
  - /assets/js/code-line-numbers.js

markdown: kramdown
kramdown:
  input: GFM
  syntax_highlighter: rouge
